#@baseUrl = http://20.120.73.82
@baseUrl = https://rutzsco-similation-service-aca.happyisland-d8fca1c2.eastus.azurecontainerapps.io/api/status

### Status  
GET  {{baseUrl}}/api/status
content-type: application/json