trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'Simulation API - BUILD'
  
variables:
  azureSubscription: 'Demo Account'
  resourceGroupName: 'Demo Account'
  clusterName: 'Demo Account'

stages:

 - stage: CI
   displayName: CI Stage 
   variables:
     kubernetesCluster: 'rutzsco-aks1'
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: 'ubuntu-latest'   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureCLI@2
              displayName: 3. Create Namespaces
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az aks get-credentials -n $(clusterName) -g $(resourceGroupName)
                  kubectl apply -f $(Pipeline.Workspace)/build/Deploy/namespace.yaml
            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                kubernetesServiceConnection: 'rutzsco-aks1'
                namespace: 'dapr-traffic-control'
                manifests: '$(Pipeline.Workspace)/build/Deploy/deployment.yaml'
                containers: 'rutzscolabcr.azurecr.io/simulation/demo-api:$(resources.pipeline.build.runName)'