trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'Simulation API - BUILD'
  
variables:
  azureSubscription: 'Demo Account'
  resourceGroupName: 'rutzsco-aks-001'
  clusterName: 'aks-rutzsco-aks-001'

stages:

 - stage: CI
   displayName: CI Stage 
   variables:
     kubernetesCluster: 'rutzsco-aks1'
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: 'ubuntu-latest'   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureCLI@2
              displayName: 1. Create Namespaces
              inputs:
                azureSubscription:  $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az aks get-credentials -n $(clusterName) -g $(resourceGroupName)
                  kubectl apply -f $(Pipeline.Workspace)/build/Infrastructure/AKS/namespace.yaml

                  export APPLICATION_VERSION_VALUE=$(resources.pipeline.build.runName)
                  envsubst < $(Pipeline.Workspace)/build/Infrastructure/AKS/deployment.yaml > $(Pipeline.Workspace)/build/Infrastructure/AKS/deployment-output.yaml

            - task: KubernetesManifest@0
              displayName: 2. Deploy to AKS
              inputs:
                action: 'deploy'
                kubernetesServiceConnection: 'rutzsco-aks-S1'
                namespace: 'simulationservice'
                manifests: '$(Pipeline.Workspace)/build/Infrastructure/AKS/deployment-output.yaml'
                containers: 'rutzscolabcr.azurecr.io/simulation/demo-api:$(resources.pipeline.build.runName)'