apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulation-service-ingress-path
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /simulationservice/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: simulationservice
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulation-service-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simulationservice
            port:
              number: 80